// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPzyd4--lmitfP5CFP34RUqnQWaE5ypqA',
    appId: '1:776544984953:web:61d65c75c20d9699ba99a8',
    messagingSenderId: '776544984953',
    projectId: 'fitnesstrackerapp-4a2dc',
    authDomain: 'fitnesstrackerapp-4a2dc.firebaseapp.com',
    storageBucket: 'fitnesstrackerapp-4a2dc.firebasestorage.app',
    measurementId: 'G-CJQEL1BVV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguWcxICOlhxKL15GkPVtlsPBTBAV-5QM',
    appId: '1:776544984953:android:854432edca09c93cba99a8',
    messagingSenderId: '776544984953',
    projectId: 'fitnesstrackerapp-4a2dc',
    storageBucket: 'fitnesstrackerapp-4a2dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAty8dtXNOSOJGZAB83AZkTvn93kIdAC4U',
    appId: '1:776544984953:ios:b4f6be09b4d9a52fba99a8',
    messagingSenderId: '776544984953',
    projectId: 'fitnesstrackerapp-4a2dc',
    storageBucket: 'fitnesstrackerapp-4a2dc.firebasestorage.app',
    iosBundleId: 'com.example.excercisesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAty8dtXNOSOJGZAB83AZkTvn93kIdAC4U',
    appId: '1:776544984953:ios:b4f6be09b4d9a52fba99a8',
    messagingSenderId: '776544984953',
    projectId: 'fitnesstrackerapp-4a2dc',
    storageBucket: 'fitnesstrackerapp-4a2dc.firebasestorage.app',
    iosBundleId: 'com.example.excercisesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPzyd4--lmitfP5CFP34RUqnQWaE5ypqA',
    appId: '1:776544984953:web:70a2de72d3afe0acba99a8',
    messagingSenderId: '776544984953',
    projectId: 'fitnesstrackerapp-4a2dc',
    authDomain: 'fitnesstrackerapp-4a2dc.firebaseapp.com',
    storageBucket: 'fitnesstrackerapp-4a2dc.firebasestorage.app',
    measurementId: 'G-MGT3RTWQ4T',
  );
}
